name: Next.js CI/CD

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Show Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.254.191.63 >> ~/.ssh/known_hosts

      - name: Fix permissions (one time)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.254.191.63 "sudo chown -R ubuntu:ubuntu /home/ubuntu/app"

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.254.191.63 "cd /home/ubuntu/app && git pull origin development && npm ci && npm run build"
